# Generated by Django 5.0 on 2024-01-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeItems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium',
            old_name='level',
            new_name='levels',
        ),
    ]
