# Generated by Django 5.0 on 2024-01-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeItems', '0002_rename_level_premium_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=100)),
                ('answer', models.TextField(max_length=500)),
            ],
        ),
    ]
